let suggestions = [
    "ToothPicks",
    "Bowls",
    "Packers",
    "Cookingspoons",
    "5 litre keg",
    "10 litre keg",
    "2.5 litre keg",
    "25 litre keg",
    "50 litre keg",
    "Chairs",
    "Egg crates",
    "Bread crates",
    "Laundry baskets",
    "Takeaway packs",
    "Coolers",
    "Foodflasks",
    "Dustbins",
    "Brooms",
    "Mops",
    "Sweeping brush",
    "Kettles",
    "Footmats",
    "Knife",
    "Filter",
    "Shoe polish and brushes",
    "Bathroom brush",
    "Tissues",
    "Iron and plastic spoon",
    "Fork",
    "Cups",
    "Toilet brush",
    "Handfan",
    "Sponge",
    "Raincoat",
    "Nylons",
    "Mortals and pestles",
    "Plate racks",
    "Flower vase",
    "Mirrors",
    "Plastic balls",
    "Ceramic plates",
    "Jugs",
    "Baskets",
    "Shopping bags",
    "Mopbuckets",
    "Straws",
    "Plastic container",
    "Grater",
    "Jars",
    "Wooden spatula",
 
];
